#!/bin/bash

cd ..

COUNT=0
CURRENT_DIR="$PWD"
PD="build_hawaii/patches"
PATCHES=(
'external/icu                   external_icu.diff'
'external/sepolicy              external_sepolicy.diff'
'external/tinyalsa              external_tinyalsa.diff'
'frameworks/av			frameworks_av.diff'
'frameworks/native		frameworks_native.diff'
'frameworks/opt/telephony	frameworks_opt_telephony.diff'
'hardware/broadcom/libbt	hardware_broadcom_libbt.diff'
'packages/services/Telephony	packages_services_Telephony.diff'
'system/core                    system_core.diff'
)

while [ "x${PATCHES[COUNT]}" != "x" ]
do
	CURRENT="${PATCHES[COUNT]}"
	FOLDER=`echo "$CURRENT" | awk '{print $1}'`
	PATCH=`echo "$CURRENT" | awk '{print $2}'`

	cd "$FOLDER"
	echo Patching "$FOLDER" ...
	git apply "$CURRENT_DIR/$PD/$PATCH"
	cd "$CURRENT_DIR"

	COUNT=$(($COUNT + 1))
done
